name: "MeshSim"
# sim-mode: "Frame-by-frame"
# sim-mode: "AFAP"
time-step: 3.33e-3
end-time: 10
solver-iters: 50
iter-acceleration: 0.95

camera-position: [25, 25, 25]

# logging: True
# logging-output-folder: "../output/convergence"
# logging-interval: 10
# log-residuals: True

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True
hdr-scaling: 0.2

ground-plane: True

objects:
  - 
    type: "TetMeshObject"
    name: "test"
    filename: "../resource/cube2.msh"
    position: [-5, 10, -5]
    scaling: [10, 10, 10]
    # material parameters
    E: 0.7 # kPa
    nu: 0.45
    density: 1e-6 # kg / mm^3
    damping-coeff: 0 #1e-6 # ?

    # render settings
    smooth-normals: False
    draw-edges: True
    draw-faces: True
    color: [1.0, 0.5, 0]