name: "MeshSim"
# sim-mode: "Frame-by-frame"
# sim-mode: "AFAP"
time-step: 1e-3 # s
end-time: 1
g-accel: 9.81e3 # mm/s^2
solver-iters: 15
iter-acceleration: 0.95
num-threads: 8
collision-margin: 1e-3

camera-position: [25, 25, 25]

# logging: True
# logging-output-folder: "../output/convergence"
# logging-interval: 10
# log-residuals: True

hdr-image-filename: "../resource/studio_1k.hdr"
create-skybox: True
hdr-scaling: 0.2
fancy-graphics: false

ground-plane: True

objects:
  - 
    type: "TetMeshObject"
    name: "test"
    filename: "../resource/tumor.msh"
    position: [0, 15, 0]
    scaling: [1, 1, 1]
    position-by-com: true
    # material parameters
    E: 0.35 # MPa (0.35 = roughly chicken breast: https://academic.oup.com/mt/article/31/2/21/7116012)
    nu: 0.45
    density: 1e-6 # kg / mm^3
    damping-coeff: 1e-6 # ?

    # render settings
    smooth-normals: False
    draw-edges: True
    draw-faces: True
    color: [1.0, 0.5, 0]

  - 
    type: "RigidSphere"
    fixed: true
    position: [0, 0, 0]
    radius: 5